services:
  postgres:
    image: postgres:alpine
    container_name: ssbw_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: una_clave_muy_segura_123
      POSTGRES_DB: ssbw
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
